platform :ios, '18.0'

target 'iosApp' do
    use_frameworks!

    pod 'composeApp', :path => '../composeApp'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
  end
end